{ config, lib, ... }:

{
  imports = [
    ./acme-dns-api.nix
    ./async-coder
    ./authoritative_dns.nix
    ./blackmagic-cam-importer
    ./downloads
    ./firefly-iii
    ./frigate.nix
    ./git.nix
    ./git-sync.nix
    ./gitea
    ./hearthd
    ./homeassistant
    ./homebox.nix
    ./protonmail-bridge.nix
    ./immich.nix
    ./jellyfin.nix
    ./journal-remote.nix
    ./mastodon
    ./matrix
    ./mautrix-discord
    ./mosquitto.nix
    ./nix-builder
    ./nix-prefetch-repos.nix
    ./nix-remote-builder.nix
    ./offline-youtube
    ./ollama.nix
    ./openclaw
    ./privatebin.nix
    ./radicale.nix
    ./renovate
    ./restic
    ./status.nix
    ./tang.nix
    ./unifi.nix
    ./version_tracker.nix
    ./zigbee2mqtt.nix
    ./zookeeper.nix
  ];
}
