---
kind: pipeline
type: docker
name: default

steps:
  - name: lint
    image: nixos/nix:2.11.1
    commands:
      - nix --extra-experimental-features 'nix-command flakes' fmt
      - git diff --exit-code

  - name: check
    image: nixos/nix:2.11.1
    commands:
      - nix --extra-experimental-features 'nix-command flakes' flake check
---
kind: signature
hmac: da929dc55d2e11b17bc29e48293b78ba1e3588df90a87e022e7dc4f1cb40d6e5

...
