---
kind: pipeline
type: docker
name: check

steps:
  - name: lint
    image: nixos/nix:2.16.1
    commands:
      - nix --extra-experimental-features 'nix-command flakes' fmt
      - git diff --exit-code

  - name: check
    image: nixos/nix:2.16.1
    commands:
      - nix --extra-experimental-features 'nix-command flakes' flake check

trigger:
  event:
    exclude:
    - tag
---
kind: signature
hmac: 27c93405b251bb8bc80c82d7271702f80753ff63a0422678e62bbe2c4a025840

...
