name: flake

on:
  push:
    branches:
      - '**'
    tags-ignore:
      - '**'

jobs:
  flake:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@692973e3d937129bcbf40652eb9f2f61becf3332 # v4.1.7
      - uses: DeterminateSystems/nix-installer-action@v13
      - uses: DeterminateSystems/magic-nix-cache-action@v7
      - name: lint
        run: |
          nix fmt
          git diff --exit-code
      - name: flake check
        run: nix flake check --all-systems
        timeout-minutes: 10
