name: flake

on:
  push:
    branches:
      - '**'
    tags-ignore:
      - '**'

jobs:
  flake:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4.2.2
      - uses: DeterminateSystems/nix-installer-action@e50d5f73bfe71c2dd0aa4218de8f4afa59f8f81d # v16
      - uses: DeterminateSystems/magic-nix-cache-action@6221693898146dc97e38ad0e013488a16477a4c4 # v9
      - name: lint
        run: |
          nix fmt -- .
          git diff --exit-code
      - name: flake check
        run: nix flake check --all-systems
        timeout-minutes: 10
