name: flake

on:
  push:
    branches:
      - '**'
    tags-ignore:
      - '**'

jobs:
  flake:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4.2.2
      - uses: DeterminateSystems/nix-installer-action@b92f66560d6f97d6576405a7bae901ab57e72b6a # v15
      - uses: DeterminateSystems/magic-nix-cache-action@87b14cf437d03d37989d87f0fa5ce4f5dc1a330b # v8
      - name: lint
        run: |
          nix fmt
          git diff --exit-code
      - name: flake check
        run: nix flake check --all-systems
        timeout-minutes: 10
