name: flake

on:
  push:
    branches:
      - '**'
    tags-ignore:
      - '**'

jobs:
  flake:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@b4ffde65f46336ab88eb53be808477a3936bae11 # v4
      - name: Prepare for Nix installation
        run: |
          apt-get update
          apt-get install -y sudo
      - uses: cachix/install-nix-action@v26
      - name: lint
        run: |
          nix fmt
          git diff --exit-code
      - name: flake check
        run: nix flake check --all-systems
        timeout-minutes: 10
