# Do not modify this file!  It was generated by ‘nixos-generate-config’
# and may be overwritten by future invocations.  Please make changes
# to /etc/nixos/configuration.nix instead.
{ config, lib, pkgs, modulesPath, ... }:

{
  imports =
    [
      (modulesPath + "/installer/scan/not-detected.nix")
    ];

  boot.initrd.availableKernelModules = [ "nvme" "ahci" "xhci_pci" "thunderbolt" "usbhid" "usb_storage" "sd_mod" ];
  boot.initrd.kernelModules = [ ];
  boot.kernelModules = [ "kvm-amd" ];
  boot.extraModulePackages = [ ];

  fileSystems."/mnt/d0" =
    {
      device = "/dev/disk/by-uuid/7e4fdfc5-33e9-401c-872f-7e4e6efa8178";
      fsType = "bcachefs";
      options = [ "noatime" "nofail" "x-systemd.device-timeout=0" ];
    };

  fileSystems."/mnt/d1" =
    {
      device = "/dev/disk/by-uuid/56c1fa70-a7e0-478c-80de-d3d9cb683a6e";
      fsType = "bcachefs";
      options = [ "noatime" "nofail" "x-systemd.device-timeout=0" ];
    };

  fileSystems."/mnt/d2" =
    {
      device = "/dev/disk/by-uuid/77ab5fb8-4be4-4907-8faa-49ba09e7da08";
      fsType = "bcachefs";
      options = [ "noatime" "nofail" "x-systemd.device-timeout=0" ];
    };

  fileSystems."/mnt/d3" =
    {
      device = "/dev/disk/by-uuid/edbcd0a3-98d9-4963-a03d-fec11b49c901";
      fsType = "bcachefs";
      options = [ "noatime" "nofail" "x-systemd.device-timeout=0" ];
    };

  fileSystems."/mnt/d4" =
    {
      device = "/dev/disk/by-uuid/41144b91-a02b-423e-8053-e62fc92c1461";
      fsType = "bcachefs";
      options = [ "noatime" "nofail" "x-systemd.device-timeout=0" ];
    };

  fileSystems."/mnt/d5" =
    {
      device = "/dev/disk/by-uuid/d3961f79-83a7-4c7e-88f0-2a6838ccaa69";
      fsType = "bcachefs";
      options = [ "noatime" "nofail" "x-systemd.device-timeout=0" ];
    };

  fileSystems."/mnt/d6" =
    {
      device = "/dev/disk/by-uuid/b2d8b371-003c-4512-b2fc-b8248ca4aa40";
      fsType = "bcachefs";
      options = [ "noatime" "nofail" "x-systemd.device-timeout=0" ];
    };

  fileSystems."/mnt/d7" =
    {
      device = "/dev/disk/by-uuid/eb8d32d0-e506-449b-8dbc-585ba05c4252";
      fsType = "btrfs";
      options = [ "noatime" "nofail" "x-systemd.device-timeout=0" ];
    };

  # Enables DHCP on each ethernet and wireless interface. In case of scripted networking
  # (the default) this is the recommended approach. When using systemd-networkd it's
  # still possible to use this option, but it's recommended to use it in conjunction
  # with explicit per-interface declarations with `networking.interfaces.<interface>.useDHCP`.
  networking.useDHCP = lib.mkDefault true;
  # networking.interfaces.enp4s0.useDHCP = lib.mkDefault true;
  # networking.interfaces.enp5s0.useDHCP = lib.mkDefault true;
  # networking.interfaces.enp6s0.useDHCP = lib.mkDefault true;
  # networking.interfaces.enp8s0.useDHCP = lib.mkDefault true;

  nixpkgs.hostPlatform = lib.mkDefault "x86_64-linux";
  hardware.cpu.amd.updateMicrocode = lib.mkDefault config.hardware.enableRedistributableFirmware;
}
